import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import * as Sentry from '@sentry/react';
import posthog from 'posthog-js';

import type { TripChoice } from '../../features/auth/services/auth-api';
import { listTrips, selectTrip } from '../../features/auth/services/auth-api';
import { API_AUTH_EVENT, type ApiAuthEventDetail } from '../../shared/api/client';
import {
  AuthContext,
  type AuthUser,
  type PendingTripSelection,
  type UserRole,
} from './auth-context';

function getStoredUser(): AuthUser | null {
  try {
    const stored = localStorage.getItem('parrot_user');
    if (!stored) return null;

    const parsed = JSON.parse(stored) as Partial<AuthUser>;
    if (parsed.tripId === undefined) {
      // Predates trip-scoped sessions (no `tripId` key at all): the backend
      // no longer honors this token shape, so drop it and force a fresh login
      // rather than trusting stale/invalid data.
      localStorage.removeItem('parrot_user');
      return null;
    }

    // Sessions created by the previous frontend do not know how many trips
    // are eligible. Default closed: hiding the switcher is safer than
    // exposing a selector that may contain only the active trip. A fresh OTP
    // or selection response records the authoritative value.
    if (parsed.canSwitchTrips === undefined) {
      parsed.canSwitchTrips = false;
      localStorage.setItem('parrot_user', JSON.stringify(parsed));
    }

    return parsed as AuthUser;
  } catch {
    return null;
  }
}

function getDevAutoLoginUser(): AuthUser | null {
  if (!import.meta.env.DEV || import.meta.env.VITE_DEV_AUTO_LOGIN !== 'true') {
    return null;
  }

  const userId = import.meta.env.VITE_DEV_USER_ID ?? '';
  const role = (import.meta.env.VITE_DEV_USER_ROLE ?? 'traveler') as UserRole;
  // VITE_DEV_TOKEN must itself be a real trip-scoped session token (the
  // middleware rejects anything else) — this should be the same trip_id
  // baked into that token, e.g. generated by scripts/gen_dev_users.py or
  // scripts/seed_marcelo_test_user.py.
  const tripId = import.meta.env.VITE_DEV_USER_TRIP_ID || null;

  return {
    userId,
    phone: import.meta.env.VITE_DEV_USER_PHONE ?? '+15550000001',
    name: import.meta.env.VITE_DEV_USER_NAME ?? 'Dev Traveler',
    token: import.meta.env.VITE_DEV_TOKEN ?? '',
    role,
    tripId,
    activeTrip: null,
    canSwitchTrips: true,
  };
}

function identify(newUser: AuthUser) {
  posthog.identify(newUser.userId, {
    telefone: newUser.phone,
    nome: newUser.name,
    papel: newUser.role,
  });
  Sentry.setUser({ id: newUser.userId, username: newUser.name ?? newUser.phone });
}

function getInitialUser(): AuthUser | null {
  const stored = getStoredUser();
  if (stored) return stored;

  const devUser = getDevAutoLoginUser();
  if (devUser) {
    // Persist synchronously during the lazy initializer (i.e. before React's
    // first commit, let alone any effect) so a child mounted once
    // `isLoggedIn` is true never races the API client's localStorage-backed
    // getToken() — same reasoning as establishSession below.
    localStorage.setItem('parrot_user', JSON.stringify(devUser));
  }
  return devUser;
}

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthUser | null>(getInitialUser);
  const [pendingSelection, setPendingSelection] = useState<PendingTripSelection | null>(null);
  const [isTripSwitcherOpen, setIsTripSwitcherOpen] = useState(false);
  const [tripSwitcherTrips, setTripSwitcherTrips] = useState<TripChoice[] | null>(null);
  const [hasNoTrips, setHasNoTrips] = useState(false);
  const recoveringMembershipTokenRef = useRef<string | null>(null);

  const clearSession = useCallback(() => {
    localStorage.removeItem('parrot_user');
    setUser(null);
    setPendingSelection(null);
    setIsTripSwitcherOpen(false);
    setTripSwitcherTrips(null);
    posthog.reset();
    Sentry.setUser(null);
  }, []);

  const logout = useCallback(() => {
    clearSession();
    setHasNoTrips(false);
  }, [clearSession]);

  const enterNoTrips = useCallback(() => {
    clearSession();
    setHasNoTrips(true);
  }, [clearSession]);

  const clearNoTrips = useCallback(() => setHasNoTrips(false), []);

  const establishSession = (newUser: AuthUser) => {
    // Persist synchronously, before setUser, and never from a useEffect:
    // React commits child effects before a parent's, so any child mounted
    // once isLoggedIn flips true (e.g. TripProvider fetching /me/trip) would
    // otherwise run before an AuthProvider effect had persisted the token,
    // reading a missing or stale value from localStorage via the API
    // client's getToken(). Writing here — inside the same event handler that
    // calls setUser — guarantees the token is already there before React
    // even starts rendering, exactly like logout()'s synchronous removeItem.
    localStorage.setItem('parrot_user', JSON.stringify(newUser));
    // One setState call per piece of state: no intermediate render can see a
    // half-replaced session (e.g. new tripId with the old token), whether
    // this is the first login or an in-app trip switch.
    setUser(newUser);
    setPendingSelection(null);
    setIsTripSwitcherOpen(false);
    setTripSwitcherTrips(null);
    setHasNoTrips(false);
    identify(newUser);
  };

  const login = (
    userId: string,
    phone: string,
    name: string | null,
    token: string,
    role: UserRole,
    tripId: string | null = null
  ) => {
    establishSession({
      userId,
      phone,
      name,
      token,
      role,
      tripId,
      activeTrip: null,
      canSwitchTrips: true,
    });
  };

  const beginTripSelection = (selection: PendingTripSelection) => {
    setPendingSelection(selection);
  };

  const completeTripSelection = (
    userId: string,
    phone: string,
    name: string | null,
    token: string,
    activeTrip: TripChoice,
    canSwitchTrips: boolean
  ) => {
    // Role is derived from activeTrip.role rather than accepted separately,
    // so a caller can't pass a role that disagrees with the chosen trip.
    establishSession({
      userId,
      phone,
      name,
      token,
      role: activeTrip.role,
      tripId: activeTrip.trip_id,
      activeTrip,
      canSwitchTrips,
    });
  };

  const openTripSwitcher = () => {
    if (!user?.canSwitchTrips) return;
    setTripSwitcherTrips(null);
    setIsTripSwitcherOpen(true);
  };
  const cancelTripSwitcher = () => setIsTripSwitcherOpen(false);

  useEffect(() => {
    if (!user) return;
    let live = true;

    const handleApiAuthError = async (event: Event) => {
      const { kind } = (event as CustomEvent<ApiAuthEventDetail>).detail;
      if (kind === 'unauthorized') {
        logout();
        return;
      }
      if (recoveringMembershipTokenRef.current === user.token) return;

      recoveringMembershipTokenRef.current = user.token;
      try {
        const result = await listTrips(user.token);
        if (!live) return;
        if (result.trips.length === 0) {
          enterNoTrips();
          return;
        }
        if (result.trips.length === 1) {
          const selected = await selectTrip(user.token, result.trips[0].trip_id);
          if (!live) return;
          completeTripSelection(
            selected.user_id,
            selected.phone,
            selected.name,
            selected.access_token,
            selected.active_trip,
            selected.can_switch_trips
          );
          return;
        }
        setTripSwitcherTrips(result.trips);
        setIsTripSwitcherOpen(true);
      } catch {
        // A 401 from the refresh emits its own unauthorized event. Other
        // failures leave the current screen intact so the user can retry.
      } finally {
        if (recoveringMembershipTokenRef.current === user.token) {
          recoveringMembershipTokenRef.current = null;
        }
      }
    };

    window.addEventListener(API_AUTH_EVENT, handleApiAuthError);
    return () => {
      live = false;
      if (recoveringMembershipTokenRef.current === user.token) {
        recoveringMembershipTokenRef.current = null;
      }
      window.removeEventListener(API_AUTH_EVENT, handleApiAuthError);
    };
  }, [enterNoTrips, logout, user]);

  return (
    <AuthContext.Provider
      value={{
        user,
        isLoggedIn: !!user,
        pendingSelection,
        isTripSwitcherOpen,
        tripSwitcherTrips,
        hasNoTrips,
        login,
        beginTripSelection,
        completeTripSelection,
        openTripSwitcher,
        cancelTripSwitcher,
        enterNoTrips,
        clearNoTrips,
        logout,
      }}
    >
      {children}
    </AuthContext.Provider>
  );
}
